# Generated by Django 5.2.1 on 2025-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ar", "Arabic"),
                ],
                default="en",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="secondary_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ar", "Arabic"),
                ],
                default="ar",
                max_length=64,
                null=True,
            ),
        ),
    ]
