# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Basic pre-commit hooks for general file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.svg$
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        exclude: \.svg$
      - id: check-ast  # Validates Python syntax

  # Black formatter for Python code
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: ['--config=pyproject.toml']
        files: ^backend/
        exclude: migrations/

  # mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: ['--config-file=pyproject.toml', '--ignore-missing-imports']
        additional_dependencies:
          - types-requests
          - django-stubs[compatible-mypy]
          - djangorestframework-stubs
        files: ^backend/.*\.py$
        exclude: (migrations/|tests/|venv/)
        # Make mypy non-blocking during pre-commit (still runs in CI)
        verbose: true
        pass_filenames: true
        stages: [manual]
