# Generated by Django 5.2.1 on 2025-09-16 14:08

import django.db.models.deletion
import notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('level', models.CharField(choices=[('elementary', 'Elementary School'), ('high_school', 'High School'), ('university', 'University'), ('masters', 'Masters')], max_length=20)),
                ('subject', models.CharField(choices=[('math', 'Math'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('literature', 'Literature'), ('economics', 'Economics')], max_length=20)),
                ('course', models.CharField(blank=True, choices=[('algebra', 'Algebra'), ('calculus', 'Calculus'), ('programming', 'Programming 101'), ('databases', 'Databases'), ('ai', 'Artificial Intelligence'), ('microeconomics', 'Microeconomics'), ('macroeconomics', 'Macroeconomics')], max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotesFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=notes.models.note_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.notes')),
            ],
        ),
    ]
