# Generated by Django 5.2.1 on 2025-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='course',
            new_name='notes_course',
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('cs', 'Computer Science'), ('it', 'Information Technology'), ('engineering', 'Engineering'), ('datasci', 'Data Science'), ('ai', 'Artificial Intelligence'), ('envsci', 'Environmental Science'), ('astronomy', 'Astronomy'), ('stats', 'Statistics'), ('robotics', 'Robotics'), ('electronics', 'Electronics'), ('psych', 'Psychology'), ('sociology', 'Sociology'), ('polisci', 'Political Science'), ('economics', 'Economics'), ('anthropology', 'Anthropology'), ('intlrel', 'International Relations'), ('criminology', 'Criminology'), ('history', 'History'), ('philosophy', 'Philosophy'), ('literature', 'Literature'), ('linguistics', 'Linguistics'), ('religion', 'Religious Studies'), ('cultural', 'Cultural Studies'), ('classics', 'Classics'), ('visualart', 'Visual Arts'), ('music', 'Music'), ('performing', 'Performing Arts'), ('architecture', 'Architecture'), ('design', 'Graphic Design'), ('film', 'Film & Media Studies'), ('photo', 'Photography'), ('fashion', 'Fashion Design'), ('business', 'Business Administration'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('hrm', 'Human Resource Management'), ('entrepreneurship', 'Entrepreneurship'), ('project', 'Project Management'), ('supplychain', 'Supply Chain Management'), ('education', 'Education'), ('earlyedu', 'Early Childhood Education'), ('specialedu', 'Special Education'), ('english', 'English Language'), ('foreignlang', 'Foreign Languages'), ('translation', 'Translation Studies'), ('tesol', 'TESOL / ESL'), ('law', 'Law'), ('legal', 'Legal Studies'), ('constitutional', 'Constitutional Law'), ('publicpolicy', 'Public Policy'), ('politicaltheory', 'Political Theory'), ('medicine', 'Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('publichealth', 'Public Health'), ('nutrition', 'Nutrition'), ('veterinary', 'Veterinary Science'), ('dentistry', 'Dentistry'), ('biomed', 'Biomedical Science'), ('physicaltherapy', 'Physical Therapy')], max_length=20),
        ),
    ]
