# Generated by Django 5.2.1 on 2025-12-19 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0005_alter_course_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the slideshow presentation", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the slideshow content",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the slideshow is visible to students",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number for conflict resolution (last-write-wins)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this slideshow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slideshows",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The teacher who created this slideshow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_slideshows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slideshow",
                "verbose_name_plural": "Slideshows",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within the slideshow (0-indexed)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional slide title (if empty, extracted from first H1 or 'Slide {order}')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown content with SpellBlock support"
                    ),
                ),
                (
                    "rendered_content",
                    models.TextField(
                        blank=True,
                        help_text="Cached HTML rendered from markdown via Spellbook",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Speaker notes visible only to teachers",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slideshow",
                    models.ForeignKey(
                        help_text="The slideshow this slide belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="slideshows.slideshow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="slideshow",
            index=models.Index(
                fields=["course", "-updated_at"], name="slideshows__course__946e86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slideshow",
            index=models.Index(
                fields=["created_by", "-updated_at"],
                name="slideshows__created_6234d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slideshow",
            index=models.Index(
                fields=["is_published", "course"], name="slideshows__is_publ_b6dc4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slide",
            index=models.Index(
                fields=["slideshow", "order"], name="slideshows__slidesh_8fadee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slide",
            unique_together={("slideshow", "order")},
        ),
    ]
