# Generated by Django 5.2.1 on 2025-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="order",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Display order within the slideshow (leave blank to auto-assign next available order)",
                null=True,
            ),
        ),
    ]
