# Generated by Django 5.2.1 on 2025-12-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slideshows", "0003_remove_slideshow_slideshows__course__946e86_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slide",
            name="title",
        ),
    ]
