# Generated by Django 5.2.1 on 2026-02-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0004_remove_slide_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='notes',
        ),
    ]
