name: Lint and Type Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend-checks:
    name: Backend Lint and Type Check (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install mypy django-stubs djangorestframework-stubs types-requests

      - name: Run mypy type check
        run: mypy backend/ --config-file=pyproject.toml

  frontend-checks:
    name: Frontend Lint and Type Check (TypeScript)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/EduLiteFrontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/EduLiteFrontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check
